LMS_HOST: local.openedx.io
CMS_HOST: studio.local.openedx.io
CMS_OAUTH2_SECRET: V8553RMCO27CBJEx3X4xTh9a
CONTACT_EMAIL: oscm@axim.org
ENABLE_HTTPS: false
LANGUAGE_CODE: en
MYSQL_ROOT_PASSWORD: 6KFFc2L9
OPENEDX_MYSQL_PASSWORD: rCZQjHdO
OPENEDX_SECRET_KEY: 6BxYaHmIkV8R3tFm9aseEWLBMG
PLATFORM_NAME: End-to-end Local CI Test
PLUGINS:
- mfe
- forum
- notes
