// Barrel for the typed API client & data-factory layer.
export { ApiError, StudioSessionExpiredError } from './errors';
export { CSRF_HEADER, CSRF_TOKEN_PATH, fetchCsrfToken } from './csrf';
export { REGISTRATION_PATH, registerLearnerAccount } from './registration';
export { ACTIVATE_PATH, activateAccount, extractActivationKey } from './activation';
export { LOGIN_SESSION_PATH, loginSession, type LoginCredentials } from './login';
export {
  DEFAULT_PASSWORD,
  learnerIdentityFor,
  newLearnerIdentity,
  type LearnerIdentity,
} from './user-identity';
export {
  COURSE_BLOCKS_PATH,
  COURSE_NAVIGATION_PATH,
  buildOutline,
  COURSEWARE_SEQUENCE_PATH,
  fetchCourseNavigation,
  fetchCourseOutline,
  fetchSequenceMetadata,
  hasHtml5Source,
  primeCoursewareForLearner,
  unitsContaining,
  unitsWithHtml5Video,
  type CourseBlock,
  type CourseNavigation,
  type CourseOutline,
  type CourseUnit,
  type NavigationBlock,
  type SequenceMetadata,
  type VideoStudentViewData,
} from './course-outline';
export {
  COURSE_PROGRESS_PATH,
  fetchCourseProgress,
  totalUnits,
  type CourseProgress,
  type ProgressSubsection,
} from './progress';
export {
  ENROLLMENT_PATH,
  COURSE_ENROLLMENT_DETAILS_PATH,
  enrollInCourseViaApi,
  fetchCourseEnrollmentDetails,
  isEnrolled,
  unenrollViaApi,
  type CourseEnrollmentDetails,
} from './enrollment';
export { COURSE_MODES_PATH, ensureCertificateBearingMode, fetchCourseModes } from './course-modes';
export { COURSE_DETAIL_PATH, fetchCourseDetail, type CourseDetail } from './course-detail';
export {
  CoursePreflightError,
  assertCourseAccessible,
  courseKeySkipReason,
} from './course-preflight';

// Studio (CMS) — see `src/api/README.md`, "Studio clients".
export { studioOrigin, studioWrite, studioWriteHeaders, STUDIO_JSON_ACCEPT } from './studio-origin';
export {
  XBLOCK_PATH,
  XBLOCK_OUTLINE_PATH,
  COURSE_INDEX_PATH,
  CONTAINER_HANDLER_PATH,
  containerChildrenPath,
  advancedComponentTypes,
  availableComponentTypes,
  courseUsageKey,
  createXBlock,
  duplicateXBlock,
  moveXBlock,
  fetchContainer,
  fetchContainerChildren,
  fetchCourseIndex,
  fetchXBlock,
  fetchXBlockOutline,
  publishXBlock,
  updateXBlock,
  type ComponentTemplate,
  type ContainerChild,
  type ContainerInfo,
  type CourseIndex,
  type CreateXBlockOptions,
  type UpdateXBlockOptions,
  type VisibilityState,
  type XBlockCategory,
  type XBlockDetail,
  type XBlockMetadata,
  type XBlockOutline,
  type XBlockWriteResult,
} from './xblock';
export {
  addToCohort,
  createCohort,
  enableCohorts,
  linkCohortToGroup,
  type Cohort,
} from './cohorts';
export { CLIPBOARD_PATH, copyToClipboard, type Clipboard } from './clipboard';
export {
  DEFAULT_SECTION_SHAPE,
  SAMPLE_YOUTUBE_ID,
  authorHtml,
  authorProblem,
  authorVideo,
  buildSection,
  firstProblem,
  problemOlx,
  type AuthoredBlock,
  type AuthoredProblem,
  type AuthoredSection,
  type AuthoredSubsection,
  type AuthoredUnit,
  type BlockSpec,
  type ProblemAnswer,
  type ProblemType,
  type SectionShape,
  type SubsectionShape,
  type UnitShape,
} from './course-content';
export {
  STUDIO_LOGIN_PATH,
  STUDIO_ME_PATH,
  establishStudioSession,
  hasStudioSession,
  fetchStudioUsername,
} from './studio-session';
export {
  STUDIO_HOME_PATH,
  STUDIO_COURSES_PATH,
  fetchStudioHome,
  listStudioCourses,
  type CourseCreatorStatus,
  type InProcessCourseAction,
  type StudioCourseList,
  type StudioCourseListQuery,
  type StudioCourseSummary,
  type StudioHome,
} from './studio-home';
export {
  REQUEST_COURSE_CREATOR_PATH,
  COURSE_CREATOR_ADMIN_PATH,
  fetchCourseCreatorStatus,
  grantCourseCreator,
  requestCourseCreator,
} from './course-creator';
export {
  CREATE_COURSE_PATH,
  COURSE_NUMBER_PREFIX,
  DEFAULT_COURSE_ORG,
  CourseExistsError,
  courseExists,
  courseKeyFor,
  createCourse,
  ensureCourse,
  newCourseIdentity,
  rerunCourse,
  waitForRerun,
  type CourseIdentity,
} from './course-factory';
export {
  ADVANCED_SETTINGS_PATH,
  COURSE_DETAILS_PATH,
  COURSE_GRADING_PATH,
  COURSE_SETTINGS_PATH,
  fetchAdvancedSettings,
  fetchCourseDetails,
  fetchCourseSettingsFlags,
  fetchGradingPolicy,
  updateAdvancedSettings,
  updateCourseDetails,
  updateGradingPolicy,
  type AdvancedSetting,
  type AdvancedSettings,
  type CourseDetails,
  type CourseSettingsFlags,
  type Grader,
  type GradingPolicy,
} from './course-settings';
export {
  COURSE_TEAM_PATH,
  COURSE_TEAM_MEMBER_PATH,
  fetchCourseTeam,
  removeCourseTeamMember,
  setCourseTeamRole,
  type CourseTeamMember,
  type CourseTeamRole,
} from './course-team';
export {
  GROUP_CONFIGURATIONS_PATH,
  GROUP_CONFIGURATIONS_WRITE_PATH,
  createContentGroups,
  fetchGroupConfigurations,
  type ContentGroup,
  type GroupConfiguration,
} from './group-configurations';
export {
  CERTIFICATES_PATH,
  CERTIFICATES_WRITE_PATH,
  CERTIFICATE_ACTIVATION_PATH,
  createCertificate,
  deleteCertificate,
  fetchCertificateConfiguration,
  resetCertificates,
  setCertificateActive,
  type Certificate,
  type CertificateConfiguration,
  type Signatory,
} from './certificates';
export {
  COURSE_APPS_PATH,
  fetchCourseApps,
  setCourseAppEnabled,
  type CourseApp,
} from './course-apps';
export {
  TABS_PATH,
  createCustomPage,
  deleteCustomPage,
  fetchCustomPages,
  setCustomPageName,
  type CustomPage,
} from './custom-pages';
export {
  EXPORT_PATH,
  EXPORT_STATUS_PATH,
  IMPORT_STATUS_PATH,
  IMPORT_SUCCESS,
  downloadCourseExport,
  fetchExportState,
  fetchImportState,
  startCourseExport,
  waitForCourseExport,
  waitForCourseImport,
  type ExportState,
  type ImportState,
} from './course-transfer';
export {
  COURSE_VALIDATION_PATH,
  COURSE_QUALITY_PATH,
  fetchCourseQuality,
  fetchCourseValidation,
  type CourseQuality,
  type CourseValidation,
} from './course-checklists';
export {
  COURSE_METADATA_PATH,
  fetchCourseMetadata,
  type CourseAccess,
  type CourseMetadata,
  type CourseTab,
} from './course-metadata';
export {
  COURSE_DISCOVERY_SEARCH_PATH,
  reindexCourse,
  searchCourseDiscovery,
  type CourseDiscoveryHit,
} from './search';

// LMS instructor dashboard — see `src/api/README.md`, "Instructor clients".
export {
  INSTRUCTOR_API_V2_PATH,
  TaskAlreadyRunningError,
  downloadReport,
  fetchCertificateGenerationEnabled,
  fetchInstructorCourse,
  fetchInstructorLearner,
  fetchInstructorTask,
  fetchLearnerProblem,
  grantCertificateException,
  grantCourseTeamRole,
  instructorApiBase,
  listCertificateGenerationHistory,
  listEnrollments,
  listInstructorTasks,
  listIssuedCertificates,
  listReports,
  listUnitExtensions,
  overrideScore,
  regenerateCertificates,
  resetAttempts,
  resolveReportUrl,
  setCourseCertificateGeneration,
  type BetaTesterModifyResult,
  type CertificateGenerationHistoryRow,
  type CourseTeamRoleV2,
  type EnrollmentModifyResult,
  type EnrollmentRow,
  type EnrollmentState,
  type GradingActionResult,
  type InstructorCourse,
  type InstructorLearner,
  type InstructorPage,
  type InstructorTab,
  type InstructorTask,
  type InstructorTaskStatus,
  type IssuedCertificate,
  type IssuedCertificateFilter,
  type LearnerListResult,
  type LearnerProblem,
  type QueuedGradingTask,
  type ReportDownload,
  type ReportType,
  type UnitExtension,
} from './instructor';
export {
  CERTIFICATE_GENERATION_ADMIN_PATH,
  ensureCertificateGenerationEnabled,
} from './certificate-generation-config';

// Content libraries v2 — see `src/api/README.md`, "Library clients".
export {
  LIBRARIES_V2_PATH,
  LibraryDeleteRestrictedError,
  LibraryExistsError,
  addCollectionItems,
  addContainerChildren,
  addLibraryTeamMember,
  commitLibrary,
  createCollection,
  createLibrary,
  createLibraryBlock,
  createLibraryContainer,
  deleteLibrary,
  fetchBlockHierarchy,
  fetchCollection,
  fetchContainerHierarchy,
  fetchLibrary,
  fetchLibraryBlock,
  fetchLibraryBlockAssets,
  fetchLibraryBlockOlx,
  fetchLibraryBlockTypes,
  fetchLibraryContainer,
  fetchLibraryContainerChildren,
  fetchLibraryTeam,
  libraryKeyFor,
  libraryOlx,
  listCollections,
  listLibraries,
  listLibraryBlocks,
  newLibrarySlug,
  publishLibraryBlock,
  publishLibraryContainer,
  renameLibraryContainer,
  setLibraryBlockOlx,
  updateLibrary,
  type ContentLibrary,
  type CreateLibraryBlockOptions,
  type CreateLibraryOptions,
  type LibraryAccessLevel,
  type LibraryBlock,
  type LibraryBlockAsset,
  type LibraryCollection,
  type LibraryContainer,
  type LibraryHierarchy,
  type LibraryHierarchyEntry,
  type LibraryItem,
  type LibraryApiPage,
  type LibraryTeamMember,
  type UpdateLibraryOptions,
} from './libraries';
export {
  DOWNSTREAMS_PATH,
  acceptSync,
  declineSync,
  fetchDownstream,
  importLibraryContent,
  listDownstreams,
  type DownstreamLink,
  type DownstreamListRow,
  type ImportLibraryContentOptions,
  type ImportedLibraryContent,
} from './library-sync';
export {
  MIGRATOR_PATH,
  addLegacyLibraryBlock,
  createLegacyLibrary,
  fetchMigration,
  isMigrationSettled,
  listLegacyLibraries,
  startMigration,
  type LegacyLibrary,
  type MigrationOptions,
  type MigrationTask,
} from './legacy-libraries';
export {
  TAGGING_BASE,
  deleteTaxonomy,
  fetchObjectTagCounts,
  fetchObjectTags,
  fetchTaxonomy,
  importTaxonomy,
  listTaxonomies,
  listTaxonomyTags,
  setObjectTags,
  setTaxonomyOrgs,
  tagCountFor,
  type AppliedTag,
  type ImportTaxonomyOptions,
  type ListTaxonomiesOptions,
  type ObjectTaxonomyTags,
  type Taxonomy,
  type TaxonomyList,
  type TaxonomyTag,
} from './tagging';
export {
  FRONTEND_SITE_CONFIG_PATH,
  MFE_CONFIG_PATH,
  agreementTypesIn,
  chromeConfigFromMfeConfig,
  chromeConfigFromSiteConfig,
  fetchAuthoringMfeConfig,
  fetchChromeConfig,
  type AgreementGating,
  type AuthoringMfeConfig,
  type ChromeConfig,
  type ChromeConfigSource,
} from './mfe-config';
export {
  AGREEMENTS_BASE,
  acceptAgreement,
  fetchAgreementRecord,
  listAgreements,
  type AgreementRecord,
  type UserAgreement,
} from './agreements';
export {
  deleteAsset,
  fetchAssets,
  fetchAllAssets,
  setAssetLock,
  uploadAsset,
  assetStudioUrl,
  type CourseAsset,
  type AssetQuery,
} from './assets';
export { createTextbook, fetchTextbooks, type Textbook, type TextbookChapter } from './textbooks';
export {
  createCourseUpdate,
  fetchCourseUpdates,
  fetchHandouts,
  type CourseUpdate,
} from './course-updates';
export { ensureAgreement, editAgreement, bumpAgreementUpdated } from './agreements-admin';
export {
  adminCsrfToken,
  adminFormErrors,
  assertAdminPage,
  countAdminResultRows,
  adminFormValue,
  adminSaveSucceeded,
  decodeAdminEntities,
  findAdminRowPk,
  openAdminForm,
  postAdminForm,
  readAdminForm,
  splitAdminDateTime,
} from './django-admin';
export { USER_ADMIN, deactivateAccount } from './user-admin';
export {
  COURSE_ACCESS_ROLE_ADMIN,
  LEGACY_COURSE_ROLES,
  countCourseAccessRoles,
  grantLegacyRole,
  listCourseAccessRoles,
  revokeLegacyRole,
  type CourseAccessRoleRow,
  type LegacyCourseRole,
} from './course-access-role-admin';
export {
  AUTHZ_BASE,
  COURSE_ROLES,
  LEGACY_ROLE_EQUIVALENTS,
  LIBRARY_ROLES,
  PLATFORM_ROLES,
  assignRole,
  authzScopeKey,
  canI,
  fetchWaffleFlagStates,
  isAuthzEnabledForCourse,
  listAssignments,
  listAuthzOrgs,
  listAuthzUsers,
  listRoleUsers,
  listRoles,
  listScopes,
  listUserAssignments,
  revokeRole,
  validateMyPermissions,
  validateUsers,
  type AuthzAssignment,
  type AuthzAssignmentQuery,
  type AuthzListQuery,
  type AuthzRoleDefinition,
  type AuthzScope,
  type AuthzScopeMember,
  type AuthzUser,
  type AuthzWriteOptions,
  type AuthzWriteOutcome,
  type AuthzWriteResult,
  type CourseRole,
  type PermissionCheck,
  type UserValidation,
  type WaffleFlagStates,
} from './authz';
export {
  MIGRATION_RUN_ADMIN,
  countMigrationRuns,
  hasCompletedMigrationRun,
  type MigrationRunQuery,
  type MigrationStatus,
  type MigrationType,
  fetchMigrationRunLedger,
  type MigrationRunLedger,
} from './authz-migration';
export {
  AUTHZ_COURSE_AUTHORING_FLAG,
  WAFFLE_COURSE_OVERRIDE_ADMIN,
  WAFFLE_ORG_OVERRIDE_ADMIN,
  clearCourseFlagOverride,
  clearOrgFlagOverride,
  setCourseFlagOverride,
  setOrgFlagOverride,
  type WaffleOverrideChoice,
  type WaffleOverrideInput,
} from './waffle';
export { lmsGet, lmsWrite } from './lms-json';
export {
  NOTIFICATION_APPS,
  fetchNotificationCount,
  fetchNotificationPreferences,
  listNotifications,
  markNotificationsRead,
  markNotificationsSeen,
  setEmailCadence,
  setNotificationPreference,
  type EmailCadence,
  type NotificationApp,
  type NotificationAppPreferences,
  type NotificationCount,
  type NotificationPage,
  type NotificationPreferences,
  type NotificationTypePreference,
  type PlatformNotification,
} from './notifications';
export {
  GENERAL_TOPIC_ID,
  createComment,
  createThread,
  deleteThread,
  fetchDiscussionCourse,
  listDiscussionTopics,
  listThreads,
  uniquePostTitle,
  updateComment,
  updateThread,
  type DiscussionComment,
  type DiscussionCourse,
  type DiscussionThread,
  type DiscussionTopic,
} from './discussions';
export {
  ORA_POINTS_POSSIBLE,
  authorStaffGradedOra,
  listOraSubmissions,
  staffAssessOra,
  submitOraResponse,
  type OraSubmission,
} from './ora';

// Learner-side APIs (Epic 14) — see `src/api/README.md`.
export {
  ADULT_YEAR_OF_BIRTH,
  fetchAccount,
  fetchPreferences,
  updateAccount,
  updatePreferences,
  type Account,
  type AccountPatch,
  type EducationLevel,
  type Preferences,
  type SocialLink,
  type SocialPlatform,
} from './accounts';
export {
  BOOKMARKS_PATH,
  addBookmark,
  listBookmarks,
  removeBookmark,
  type Bookmark,
} from './bookmarks';
export { fetchResumePoint, recordCompletion, type ResumePoint } from './completion';
export {
  CHANGE_EMAIL_SETTINGS_PATH,
  LEARNER_HOME_INIT_PATH,
  fetchLearnerHome,
  learnerHomeCourse,
  setCourseEmailOptIn,
  type LearnerHome,
  type LearnerHomeCourse,
  type LearnerHomeEnrollment,
} from './learner-home';
export { fetchUserTours, type CourseHomeTourStatus, type UserTours } from './user-tours';
export {
  courseTool,
  fetchCourseHomeOutline,
  type CourseHomeOutline,
  type CourseTool,
} from './course-home';
